__base__:
    - ../../default_runtime.yaml
    - ../../datasets/operation_surgery/operation_surgery.yaml
    - ../../schedules/schedule_200e.yaml
    - ../../models/resnet/resnet50_cifar.yaml

model:
    init_args:
        model:
            init_args:
                head:
                    num_classes: 3
